<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span><ul class="toc-item"><li><span><a href="#Импорт-библиотек" data-toc-modified-id="Импорт-библиотек-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Импорт библиотек</a></span></li><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Обзор-загруженных-данных" data-toc-modified-id="Обзор-загруженных-данных-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Обзор загруженных данных</a></span></li></ul></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Создадим-признаки:" data-toc-modified-id="Создадим-признаки:-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Создадим признаки:</a></span></li><li><span><a href="#Построим-модель-для-исходных-данных:" data-toc-modified-id="Построим-модель-для-исходных-данных:-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Построим модель для исходных данных:</a></span></li><li><span><a href="#Создадим-новую-матрицу:" data-toc-modified-id="Создадим-новую-матрицу:-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Создадим новую матрицу:</a></span></li><li><span><a href="#Умножим-исходную-матрицу-на-полученную-обратную:" data-toc-modified-id="Умножим-исходную-матрицу-на-полученную-обратную:-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Умножим исходную матрицу на полученную обратную:</a></span></li><li><span><a href="#Построим-новую-модель-и-определим-ее-качество:" data-toc-modified-id="Построим-новую-модель-и-определим-ее-качество:-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Построим новую модель и определим ее качество:</a></span></li></ul></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

### Импорт библиотек

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

### Загрузка данных

In [2]:
try:
    data = pd.read_csv('/datasets/insurance.csv')
except:
    data = pd.read_csv('insurance.csv')

### Обзор загруженных данных

In [3]:
def data_check (data_file):
    display(data_file.head())
    data_file.info()
    print('Количество пропусков', data_file.isna().sum().sum())
    print('Количество дубликатов:', sum(data_file.duplicated()))
    return 

In [4]:
data_check(data)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB
Количество пропусков 0
Количество дубликатов: 153


**Удалим дубликаты в таблице:**

In [5]:
data.drop_duplicates(inplace=True)

**Изменим тип данных возраста:**

In [6]:
data['Возраст'] = data['Возраст'].astype('int64')

In [7]:
data_check(data)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1       41   49600.0            1                  0
1    0       46   38000.0            1                  1
2    0       29   21000.0            0                  0
3    0       21   41700.0            2                  0
4    1       28   26100.0            0                  0

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4847 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                4847 non-null   int64  
 1   Возраст            4847 non-null   int64  
 2   Зарплата           4847 non-null   float64
 3   Члены семьи        4847 non-null   int64  
 4   Страховые выплаты  4847 non-null   int64  
dtypes: float64(1), int64(4)
memory usage: 227.2 KB
Количество пропусков 0
Количество дубликатов: 0


**Вывод:**

- Пропусков в данных нет;
- Тип данных столбца "Возраст" был изменен на int64, так как возраст не имеет десятичных значений;
- Были найдены и удалены дубликаты.

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** При умножении признаков на обратимую матрицу, качество линейной регрессии не изменится:

**Обоснование:** 

1) Для определения качества мы должны получить новую матрицу X1 умножением на исходной на обратимую матрицу P:

$X1 = X * P$

2) Согласное формуле обучения, мы можем построить аналогичную формулу для новой матрицы:

$w1 = ((XP)^TXP)^{-1}(XP)^Ty$

3) Раскроем скобки выражения:

$w1 = (P^TX^TXP)^{-1}P^TX^Ty$

$w1 = P^{-1}(X^TX)^{-1}(P^T)^{-1}P^TX^Ty$

4) $(P^T)^{-1}P^T$ - равнозначно единичной матрице E, так как P обратима, то:

$w1 = P^{-1}(X^TX)^{-1}EX^Ty = P^{-1}(X^TX)^{-1}X^Ty$

5) Имея формулу обучения $w = (X^TX)^{-1}X^Ty$ мы получим формулу для w1: 

$w1 = P^{-1}(X^TX)^{-1}X^Ty = P^{-1}w$

6) Напишем аналогичную формулу предсказания для а1:

$a1 = X1w1 - XPP^{-1}w$

7) Так как у нас обратная матрица, то $PP^{-1}$ равна Е:

$a1 = XPP^{-1}w = XEw = Xw$

8) $Xw = a$, значит $a1 = a$

## Алгоритм преобразования

**Алгоритм**

Для решения задания, нужно сделать следующие шаги:

- Нужно сформировать матрицу признаков и сгенерировать другую со схожими параметрами
- Умножить матрицы друг на друга
- Рассчитать качества модели матриц как исходной, так и полученной.

**Обоснование**

Согласно второму пункту, предсказания на исходной и изначальной матрице не должны отличаться, как и значение качества. Рассчитаем метрику R2 для матриц.

## Проверка алгоритма

### Создадим признаки:

In [8]:
features = data.drop('Страховые выплаты', axis=1)
target = data['Страховые выплаты']

### Построим модель для исходных данных:

In [9]:
model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)
r2 = r2_score(target, predictions)
print('Метрика R2', r2)

Метрика R2 0.4302010044852067


### Создадим новую матрицу:

In [10]:
matrix_new = np.random.normal(size=(4,4))

In [11]:
matrix_new

array([[-0.10030522,  0.21635855,  0.02178968,  1.13043353],
       [ 0.462702  ,  0.74649116,  0.76678113,  0.75838139],
       [-0.10542058,  1.60035983, -0.08222651,  0.40758256],
       [ 0.67276187, -0.64296001,  0.97437401,  0.33042514]])

**Обратим матрицу для дальнейшей работы:**

In [12]:
matrix_inv = np.linalg.inv(matrix_new)

In [13]:
matrix_inv

array([[ 11.05688096, -80.35397432,  63.44311251,  68.34099643],
       [ -0.23645071,  -0.21619978,   0.85721498,   0.24776512],
       [ -8.49387006,  58.12193864, -45.38906778, -48.35300511],
       [  2.07469059,  -8.20889081,   6.340243  ,   6.94861694]])

### Умножим исходную матрицу на полученную обратную:

**Конвертируем исходные данные в матрицу:**

In [14]:
matrix = features.values

In [15]:
matrix

array([[1.00e+00, 4.10e+01, 4.96e+04, 1.00e+00],
       [0.00e+00, 4.60e+01, 3.80e+04, 1.00e+00],
       [0.00e+00, 2.90e+01, 2.10e+04, 0.00e+00],
       ...,
       [0.00e+00, 2.00e+01, 3.39e+04, 2.00e+00],
       [1.00e+00, 2.20e+01, 3.27e+04, 3.00e+00],
       [1.00e+00, 2.80e+01, 4.06e+04, 1.00e+00]])

**Умножим матрицы:**

In [16]:
matrix_result = matrix @ matrix_inv

**Сформируем таблицу из полученной матрицы:**

In [17]:
features_result = pd.DataFrame(matrix_result, columns=features.columns)

In [18]:
features_result.head()

Пол       Возраст      Зарплата   Члены семьи
0 -421292.518013  2.882751e+06 -2.251193e+06 -2.398224e+06
1 -322775.864421  2.208616e+06 -1.724739e+06 -1.837396e+06
2 -178378.128385  1.220554e+06 -9.531456e+05 -1.015406e+06
3 -354195.197695  2.423664e+06 -1.892693e+06 -2.016301e+06
4 -221685.572373  1.516896e+06 -1.184567e+06 -1.261938e+06

### Построим новую модель и определим ее качество:

In [19]:
model = LinearRegression()
model.fit(features_result, target)
predictions = model.predict(features_result)
r2 = r2_score(target, predictions)
print('Метрика R2', r2)

Метрика R2 0.4302010044850163


**Вывод:** Метрики качества обеих моделей одинаковые, значит умножение на случайную матрицу может служить методом защиты данных пользователей.

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [x]  Весь код выполняется без ошибок
- [x]  Ячейки с кодом расположены в порядке исполнения
- [x]  Выполнен шаг 1: данные загружены
- [x]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [x]  Указан правильный вариант ответа
    - [x]  Вариант обоснован
- [x]  Выполнен шаг 3: предложен алгоритм преобразования
    - [x]  Алгоритм описан
    - [x]  Алгоритм обоснован
- [x]  Выполнен шаг 4: алгоритм проверен
    - [x]  Алгоритм реализован
    - [x]  Проведено сравнение качества моделей до и после преобразования